print("#####################")
print("#                   #")
print("#  Esse é o         #")
print("#  famigerado       #")
print("#  Ola mundo        #")
print("#                   #")
print("#  By Lucas         #")
print("#                   #")
print("#                   #")
print("#                   #")
print("#####################")
